
ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}

LABEL maintainer="hedeqiang <hedeqiang@88.com>"

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>